### PR TITLE
test: AU-1407: Possibility to unit test ATV module

### PR DESCRIPTION
**Pull request by Puavo**
# [AU-1407](https://helsinkisolutionoffice.atlassian.net/browse/AU-1407)

## What was done

Add unit tests for ATV module. This is helper PR to test them. Do not merge until all versions are properly handled.

Check other PR:s for more interesting changes.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1407-tests-for-atv-module`
  * `composer install`
  * check Readme.md for correct command to run the tests

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Other PRs

* Merged: https://github.com/City-of-Helsinki/drupal-module-helfi-atv/pull/14
* https://github.com/City-of-Helsinki/drupal-module-helfi-atv/pull/15
* https://github.com/City-of-Helsinki/drupal-module-helfi-helsinki-profiili/pull/16

[AU-1407]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jiisuominen — COMMENTED** [review]
ATV päivitetty -> [0.9.10](https://github.com/City-of-Helsinki/drupal-module-helfi-atv/releases/tag/0.9.10)

**Review by jiisuominen — CHANGES_REQUESTED** [review]
Tän vois päivittää tosiaankin tohon uuteen ATV versioon.

**Comment by jiisuominen** [comment]
@Puavo miks tää ei oo edenny?

**Comment by Puavo** [comment]
ATV moduuliin tehtyjä bugikorjauksia on täällä https://github.com/City-of-Helsinki/drupal-module-helfi-atv/pull/15 Päivitän tämän pullarin tämän päivän aikana.

**Comment by jiisuominen** [comment]
> ATV moduuliin tehtyjä bugikorjauksia on täällä [City-of-Helsinki/drupal-module-helfi-atv#15](https://github.com/City-of-Helsinki/drupal-module-helfi-atv/pull/15) Päivitän tämän pullarin tämän päivän aikana.

Oliks tää tehtynä?

**Comment by Puavo** [comment]
> > ATV moduuliin tehtyjä bugikorjauksia on täällä [City-of-Helsinki/drupal-module-helfi-atv#15](https://github.com/City-of-Helsinki/drupal-module-helfi-atv/pull/15) Päivitän tämän pullarin tämän päivän aikana.
> 
> Oliks tää tehtynä?

Yksi committi odotti pushaamista.

Mä resolvaan konfliktin seuraavaksi.

**Comment by jiisuominen** [comment]
`🔥 [local] [hel-fi-drupal-grant-applications.docker.so] /app $ vendor/bin/phpunit -c public/core public/modules/custom/grants_metadata
PHPUnit 9.6.12 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

Testing /app/public/modules/custom/grants_metadata
....                                                                4 / 4 (100%)

Time: 00:05.513, Memory: 14.00 MB

OK (4 tests, 1046 assertions)

Unsilenced deprecation notices (1)

  1x: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
    1x in AtvSchemaTest::testKuvaProjektiHakemus from Drupal\Tests\grants_metadata\Kernel`

**Review by jiisuominen — CHANGES_REQUESTED** [review]
`🔥 [local] [hel-fi-drupal-grant-applications.docker.so] /app $ vendor/bin/phpunit -c public/core public/modules/contrib/helfi_atv
PHPUnit 9.6.10 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

No tests executed!

Remaining direct deprecation notices (4)

  1x: The "Drupal\Component\EventDispatcher\Event" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.
    1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit

  1x: The "PHPUnit\TextUI\DefaultResultPrinter" class is considered internal This class is not covered by the backward compatibility promise for PHPUnit. It may change without further notice. You should not use it from "Drupal\Tests\Listeners\HtmlOutputPrinter".
    1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit

  1x: The "Drupal\Tests\Listeners\DrupalListener" class implements "PHPUnit\Framework\TestListener" that is deprecated.
    1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit

  1x: The "Drupal\Tests\Listeners\DrupalListener" class uses "PHPUnit\Framework\TestListenerDefaultImplementation" that is deprecated The `TestListener` interface is deprecated.
    1x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit`

**Comment by Puavo** [comment]
```Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!```

ongelma on Works as intended koska core tukee vanhempia phpunit-versioita.

https://www.drupal.org/project/drupal/issues/3334645

**Pull request closed without merging**
