### PR TITLE
fix: AU-1845: Remove context from personal info labels

### PR DESCRIPTION
**Pull request by strangeworlder**
# [AU-1845](https://helsinkisolutionoffice.atlassian.net/browse/AU-1845)

## What was done

* Private person info translations

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1845-private-person-labels`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Log in as private person
* [ ] Go to [asukasosallisuus pienavustus](https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/asukasosallisuus_pienavustushake)
* [ ] See that the hakijan tiedot is translated
* [ ] check swedish while you're at it.
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

[AU-1845]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by suvikankare — APPROVED** [review]

**Comment by oskarimysteerio** [comment]
image
Mulla näyttäis olevan SV puoli jännästi ruotsi / englantia sekaisin

**Comment by Alexander-Tallqvist-Siili** [comment]
@suvikankare Testailin tätä kans. Sama ongelma kun Oskarilla.

**Comment by strangeworlder** [comment]
@oskarimysteerio , @Alexander-Tallqvist-Siili - katsoisiko jompikumpi, että toimiiko nyt? Pitäisi olla korjattu.

**Comment by Alexander-Tallqvist-Siili** [comment]
@strangeworlder Voin kurkata.

**Comment by Alexander-Tallqvist-Siili** [comment]
@strangeworlder Sanalta "City" taitaa vielä puuttua sv-käännös:

Screenshot 2023-11-07 at 13 23 03

**Review by suvikankare — APPROVED** [review]

**Pull request merged**
