### PR TITLE
feat: AU-758 Summation component

### PR DESCRIPTION
**Pull request by strangeworlder**
# [AU-758](https://helsinkisolutionoffice.atlassian.net/browse/AU-758)

Fix the non-functioning old module. Now summation field can be added to the form.

## What was done

* Made a new version of the Summation Field module that was a dud before

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-325-table-component`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Log in as admin.
* [ ] Go edit KASKO yleisavustushakemus
* [ ] Add a new element to the Avustuslaji section of the type Grants Webform Summation Field.
* [ ] Select the Avustukset: amount field as the one getting collected
* [ ] Select Euro as the type
* [ ] Set the title display as invisible.
* [ ] Save the element.
* [ ] In a different browser, clear browser cache
* [ ] go to https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/kasvatus_ja_koulutus_yleisavustu and navigate to the second page. Add numbers to the avustuslaji. See that the summation field increases as needed.
* [ ] Go back to your admin browser
* [ ] Add two new text fields to the first page. Doesn't matter what they are.
* [ ] Add a Grants Webform Summation Field to the first page.
* [ ] Select the two new text fields as the ones getting collected
* [ ] Select integer as the type
* [ ] Save the element
* [ ] In your other broswer, reload your page that is on the form page.
* [ ] Add numbers to your new fields
* [ ] See that the summation field increases in value.
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR needs to be visually reviewed by a designer (Heikki)

[AU-758]: https://helsinkisolutionoffice.atlassian.net/browse/AU-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jiisuominen** [comment]
image

New text fields are not available on the summation component?

Adding existing fields works as expected.

**Review by jiisuominen — CHANGES_REQUESTED** [review]
Yeah, new fields are not showing up, otherwise ok.

**Comment by strangeworlder** [comment]
> Yeah, new fields are not showing up, otherwise ok.

This is interesting, because for me, they are showing up as expected. Sounds like some strange cache issue.

**Review by jiisuominen — COMMENTED** [review]
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&branch=feature%2FAU-325-table-component&id=City-of-Helsinki_avustusasiointi

**Review by jiisuominen — APPROVED** [review]

**Review by jiisuominen — APPROVED** [review]

**Pull request merged**
