### PR TITLE
fix: AU-1247, AU-1430, AU-1437 Kulttuuri taiteen perusopetus fixes

### PR DESCRIPTION
**Pull request by strangeworlder**
# Various

## What was done

* [AU-1247](https://helsinkisolutionoffice.atlassian.net/browse/AU-1247): Translations from excel to perusopetus
* [AU-1430](https://helsinkisolutionoffice.atlassian.net/browse/AU-1430): Change from 3 to 4 boxes
* [AU-1437](https://helsinkisolutionoffice.atlassian.net/browse/AU-1437): fix problems in premises component

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1430-1437-1332-1247-kuva-fixes`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Log in as admin
* [ ] Go to config ignore, remove the webform line and save
* [ ] run `make drush-cim`
* [ ] run `make drush-gwi` 
* [ ] As admin, change so that the Perusopetus form is open
* [ ] Log in as user
* [ ] Fill and send the form in English. See that the texts match those in the Excel (AU-1247) and that the form sends out things nciely
* [ ] Fill and send the form in Swedish. See that the texts match those in the Excel (AU-1247) and that the form still sends out things nicely
* [ ] Go to page 4. 
* [ ] See that the grouping of the children is now by level of education, not by gender (4 boxes, not 3) (AU-1430)
* [ ] Add a premise. See that there is no tilan tyyppi and the empty selection for toimiala (after you select that city owns the premise) reads "- ei tietoa -" (AU-1437)
* [ ] Check that code follows our standards

[AU-1247]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1430]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1437]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jiisuominen** [comment]
image

BTW jos ajaa make fresh, se tuo muut konffit, ja tuo drush gwi tuo lomakkeet + käännökset riippumatta ignoretilasta.

**Comment by jiisuominen** [comment]
image

Jos teet muutoksia suoraan YAMLiin, niin varmista että rakenne on oikein. Tää hidastaa tosi paljon testaamista yms. Ja ennen muuta aiheuttaa pahaa hämmennystä jos näitä joutuu jälkikäteen selvittelemään

**Comment by strangeworlder** [comment]
duplikaattiavain korjattu

**Comment by jiisuominen** [comment]
> duplikaattiavain korjattu

haha saadaa siis konflikti ku mäki korjasin sen et sain lomakkeen muuten testattua. katotaa miten käy

**Review by jiisuominen — APPROVED** [review]
Small fixes but good.

**Pull request merged**
