### PR TITLE
fix: AU-1220: Lint fixes: grants_profile module to a better shape

### PR DESCRIPTION
**Pull request by strangeworlder**
# [AU-1220](https://helsinkisolutionoffice.atlassian.net/browse/AU-1220)

## What was done

* Refactored individual methods to lessen complexity of individual methods
* Moved re-used code from individual form classes to the base form class
* Removed email field from private person profile form
* Made the address fields in a private person profile form into a fieldset to match the other forms.
* Made it so that there needs to be at least one Official for Unregistered communities
* Removed unused things in code
* General cleaning up

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1220-profile-further-grants_profile`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [x] Take a comfortable position, this will take a while.
* [x] Log in to your development enviornment with a Henkilötunnus you haven't done with before.
* [x] Choose yksityishenkilö as your asiointirooli (there should be no errors in creating a new yksityishenkilö)
* [x] On the profile form, empty all fields you can, and with the development tools of your browser, remove all `required="required"` from the input fields that are now empty. Try to save the form and see that all the fields that are not filled give out an error from the server side. Do not remove fieldsets if it would be possible, that's the next step.
* [x] Now, fill out the fields, but remove the bank account so that there are no bank accounts (even empty ones). Try to save the form and get the error from the server about there having to have one bank account.
* [x] Fill out the profile and save. See that the profile is displayed correctly on the profile page (disregard the english texts on the profile page, there's a ticket out there for those)
* [x] Go to a new [Kuva Projektihakemus](https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/kuva_projekti) and fill it and see that everything goes forward just fine.
* [x] [Change asiointirooli](https://hel-fi-drupal-grant-applications.docker.so/fi/asiointirooli-valtuutus) to Unregistered community and create a new unregistered community (since you shouldn't have those as this is a hetu you haven't used before. If there are unregistered communities here, go back to step one)
* [x] On the profile form, empty all fields you can, and with the development tools of your browser, remove all `required="required"` from the input fields that are now empty. Try to save the form and see that all the fields that are not filled give out an error from the server side. Do not remove fieldsets if it would be possible, that's the next step.
* [x] Now, fill out the fields, but remove the bank account and official fieldsets with the "poista" buttons on each so that you have no officials or bank accounts. Try to save and see that you get an error from the server about having to have one bank account and one official.
* [x] Fill out the profile properly, but choose "muu" as the role of the toiminnasta vastaava henkilö. Save and get an error about having to have at least one "vastuuhenkilö" in the mix.
* [x] Fill out the profile correctly (with vastuuhenkilö as an official role) and save. See that the profile is displayed correctly on the profile page
* [x] Go to a new [Kuva Projektihakemus](https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/kuva_projekti) and fill it and see that everything goes forward just fine.
* [x] [Change asiointirooli](https://hel-fi-drupal-grant-applications.docker.so/fi/asiointirooli-valtuutus) to Registered community and select one.
* [x] On the profile form, empty all fields you can, and with the development tools of your browser, remove all `required="required"` from the input fields that are now empty. Try to save the form and see that all the fields that are not filled give out an error from the server side. Do not remove fieldsets if it would be possible, that's the next step.
* [x] Now, fill out the fields, but remove the address, bank account and official fieldsets with the "poista" buttons on each so that you have no addresses, officials or bank accounts. Try to save and see that you get an error from the server about having to have one bank account and one address.
* [x] Fill out the profile properly, and choose "muu" as the role of the toiminnasta vastaava henkilö. Save see that it works properly. See that the profile is displayed correctly on the profile page.
* [x] Go to a new [Kuva Projektihakemus](https://hel-fi-drupal-grant-applications.docker.so/fi/uusi-hakemus/kuva_projekti) and fill it and see that everything goes forward just fine.
* [x] Check that code follows our standards. Do this diligently.
* [ ] Bonus task: Refactor GrantsProfileService.php to be less complex.

[AU-1220]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by oskarimysteerio** [comment]
Rekisteröity yhdistys - Tilinumero:

Tässä varmaan toi otsikko pitäis vaihtaa takaisin? On nyt "Henkilökohtainen tilinumero" - Samoin lukee "Voit antaa vain oman tilisi tiedot".

Lokaali screenshot:
image

Stage:
image

**Comment by strangeworlder** [comment]
> Rekisteröity yhdistys - Tilinumero:
> 
> Tässä varmaan toi otsikko pitäis vaihtaa takaisin? On nyt "Henkilökohtainen tilinumero" - Samoin lukee "Voit antaa vain oman tilisi tiedot".
> 
> Lokaali screenshot: image
> 
> Stage: image

Ah, good catch. Toi oli jossain kohtaa työn alla, mutta päädyin johonkin sivupolkuun. korjataan.

**Comment by strangeworlder** [comment]
@oskarimysteerio - pankkitilin tekstit profiilityypin mukaan lisätty.

**Comment by jiisuominen** [comment]
image

Yksityishenkilö -> Tilinumeron puuttumisesta virheilmotus vois olla tossa inline?

**Comment by jiisuominen** [comment]
image

Toimintaryhmä -> Tilinumeron ja vastuuhenkilön puuttumisesta inlinevirhe?

**Review by jiisuominen — CHANGES_REQUESTED** [review]
Noi inline virheilmotukset vois vielä listätä lomakkeille.

**Comment by jiisuominen** [comment]
Tein GrantsProfileService refaktorille oman tiketin: https://helsinkisolutionoffice.atlassian.net/browse/AU-1803

**Comment by strangeworlder** [comment]
@jiisuominen - tein noista inline-virheistä oman tiksun, koska niitä ei ole missään tällä profiilissa hetkellä: https://helsinkisolutionoffice.atlassian.net/browse/AU-1804

**Review by jiisuominen — APPROVED** [review]

**Pull request merged**
