### PR TITLE
UHF-9250 Preinstall configurations for v3 [Part 1]

### PR DESCRIPTION
**Pull request by khalima**
# [UHF-9250](https://helsinkisolutionoffice.atlassian.net/browse/UHF-9250) Platform config V3 update - Part 1

This PR is consists of custom update hook and preinstalled configurations which will ease up the installation of platform config v3. Otherwise the site-install will just fail.

❗ This PR needs to be merged on `develop` & `main` before the actual platform config v3 PR ❗ 

## What was done

* Added user roles: Editor, Super administrator to tackle platform config v3 installation issues.
* Preinstall views bulk operations and views bulk edit.
* Added initial settings for content lock.
* Update banner design before the platfrom v3 change.
* Added simple_sitemap default configuration.
* Preinstall filter formats and editor settings.
* Preinstall simple_sitemap settings for nodes and tpr entities.
* Preinstall simple sitemap configuration as it would break during platform config v3 update.
* Uninstall config update module.
* Added a update function to switch all sidebar field formats to minimal field formats.

## How to install

* Make sure your instance is up and running on develop branch.
  * `git checkout develop`
  * `make fresh`
* Switch to this branch
  * `git checkout UHF-9250_preinstall_configurations_for_v3`
*  Run `make drush-deploy`

## How to test

* [ ] Check that the site installs normally and there are no errors during installation.
* [ ] Check that code follows our standards

## Automatic- / Regression tests

* [ ] This PR makes no changes that effects any tests. (This will be caught in automatic testing later on, but please, please run regression tests always on PR before asking for a review)
* [ ] This PR passes regression tests. (`make test-pw`)

## Other PRs

* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1052

[UHF-9250]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jiisuominen** [comment]
Some prints in the db updates:
`> >  [warning] The "field_lower_content" at "tpr_service:tpr_service" references the "paragraph:event_list" entity type that does not exist. Please take action. ResourceTypeRepository.php:454`

And same in config import. A LOT more:
`>  [warning] The "field_lower_content" at "tpr_service:tpr_service" references the "paragraph:event_list" entity type that does not exist. Please take action. ResourceTypeRepository.php:454`

Do we need to worry about these?

**Comment by jiisuominen** [comment]
Subtheme does not compile.

` error  ModuleNotFoundError                                                                                                                         8:42:41 AM
Module not found: Error: Can't resolve 'src/js/accordion.js' in '/app/public/themes/custom/hdbt_subtheme'
Did you mean './src/js/accordion.js'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (/app/public/themes/custom/hdbt_subtheme/node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.`

This with 6 modules:
- src/js/accordion.js
- src/js/common.js
- src/js/dialog.js
- src/js/matomo.js
- src/js/restrictedDatepicker.js
- src/js/webform.element.help.js

Are these imported incorrectly in our subtheme?

**Comment by jiisuominen** [comment]
> Subtheme does not compile.
> 
> ` error ModuleNotFoundError 8:42:41 AM Module not found: Error: Can't resolve 'src/js/accordion.js' in '/app/public/themes/custom/hdbt_subtheme' Did you mean './src/js/accordion.js'? Requests that should resolve in the current directory need to start with './'. Requests that start with a name are treated as module requests and resolve within module directories (/app/public/themes/custom/hdbt_subtheme/node_modules). If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.`
> 
> This with 6 modules:
> 
> * src/js/accordion.js
> * src/js/common.js
> * src/js/dialog.js
> * src/js/matomo.js
> * src/js/restrictedDatepicker.js
> * src/js/webform.element.help.js
> 
> Are these imported incorrectly in our subtheme?

Actually, merging our current development branch to this one seemed to fix this issue.

**Comment by jiisuominen** [comment]
@strangeworlder this breaks our styles, even rebuilt those and still missing some things:

image

**Comment by khalima** [comment]
> Some prints in the db updates: `> > [warning] The "field_lower_content" at "tpr_service:tpr_service" references the "paragraph:event_list" entity type that does not exist. Please take action. ResourceTypeRepository.php:454`
> 
> And same in config import. A LOT more: `> [warning] The "field_lower_content" at "tpr_service:tpr_service" references the "paragraph:event_list" entity type that does not exist. Please take action. ResourceTypeRepository.php:454`
> 
> Do we need to worry about these?

No need to worry about these. These references will be taken care of in the [Part 2](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1052).

**Comment by strangeworlder** [comment]
> @strangeworlder this breaks our styles, even rebuilt those and still missing some things:

The update causes stricter rules to be applied to processed_text's text format. Changing all of our processed texts to webform markups (that are used in other parts of our forms for the exact same purpose) fixes this problem.

**Review by jiisuominen — APPROVED** [review]
Seems to work. Let's test in STAGE.

**Pull request merged**
