### PR TITLE
feat: AU-1222, AU-1227, AU-1243: Unregistered Community changes.

### PR DESCRIPTION
**Pull request by strangeworlder**
# AU-1222, AU-1227, AU-1243

## What was done

* [AU-1222](https://helsinkisolutionoffice.atlassian.net/browse/AU-1222): Everything here except the tooltips for fieldsets. These are replaced with descriptions. Will have to talk with Heikki about this.
* [AU-1227](https://helsinkisolutionoffice.atlassian.net/browse/AU-1227): Everything here.
* [AU-1243](https://helsinkisolutionoffice.atlassian.net/browse/AU-1243): These, but according to the visual specs in AU-1222, above.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout feature/AU-1222-1227-unregistered-community`
  * `make fresh`
  * `make drush-gwi`
* Run `make drush-cr`

## How to test

* [x] Log in, select unregistered community as your role
* [x] AU-1222: Go to your edit profile page. See that the top box contains the basic information for a private person. And that there is a link (that matches the link on the private person page) to Helsinki Profiili.
* [x] AU-1222: See that you can fill one and only one address and that it is prefilled, but not read only
* [x] AU-1222: See that the bank account details are open by default and that the SSN and the name of the owner of the bank account are filled in by default and cannot be edited.
* [x] AU-1222: See that you can add a second bank account in the profile
* [x] AU-1222: See that you can delete both bank accounts from the profile, but you get an error in saving the form if you do.
* [ ] AU-1222: Save the form. See that the info you inputted is on the profile page.
* [x] AU-1222: Go back to edit profile page. Switch languages. See that the Unregistered Profile Edit Page works in all three languages.
* [x] AU-1227: Make sure you are logged in as unregistered community.
* [x] AU-1227: Go to Kuva Projektihakemus. See that the first page has an information box that matches the box in the layout
* [x] AU-1227: See that the fillable fields on the first page are not duplciates of other fields that are now in the box above
* [x] AU-1227: Fill the form, send it. See that it maps out right.
* [ ] AU-1227: Check that all forms work correctly. All first pages have been affected.
* [x] AU-1243: Change your role to private person. Go to edit your profile. See that the info text about filling the form is a notification at the start of the form (see the layout from 1222)
* [x] AU-1243: Change your role to registered community. Go to edit your profile. See that the info text about filling the form is a notification at the start of the form (see the layout from 1222)
* [x] AU-1227: in another browser, log in as admin.
* [x] AU-1227: Check that all forms are still editable. There has been changes to the forms on the yml level, so go to each form in the admin, edit one item and save it. If saving works, the yml is good.
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

[AU-1222]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1227]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AU-1243]: https://helsinkisolutionoffice.atlassian.net/browse/AU-1243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jiisuominen — CHANGES_REQUESTED** [review]
image

Profile page.

**Comment by jiisuominen** [comment]
`AU-1227: Check that all forms work correctly. All first pages have been affected.`

Vain kuva projektiavustus toimintaryhmällä?

**Comment by jiisuominen** [comment]
image

yksityishenkilön lomakkeelta puuttuu helsinkiprofiili linkki

**Comment by jiisuominen** [comment]
image
this

**Comment by jiisuominen** [comment]
image
this

**Comment by jiisuominen** [comment]
image
phpcs

**Comment by jiisuominen** [comment]
```
- *Warning*: Undefined array key 0 in *Drupal\grants_handler\Plugin\WebformElement\CommunityOfficialsComposite->formatTextItemValue()* (line *44* of *modules/custom/grants_handler/src/Plugin/WebformElement/CommunityOfficialsComposite.php*).
- *Warning*: Undefined array key 0 in *Drupal\grants_handler\Plugin\WebformElement\CommunityOfficialsComposite->formatTextItemValue()* (line *44* of *modules/custom/grants_handler/src/Plugin/WebformElement/CommunityOfficialsComposite.php*).
```

**Comment by strangeworlder** [comment]
@jiisuominen lukuunottamatta tota yhteyshenkilön virhettä kommentit pitäisi olla nyt korjattu. Ja siitä virheestä tosiaan oma tiksu.

**Review by jiisuominen — APPROVED** [review]

**Pull request merged**
