### PR TITLE
AU-819: General robot tests improvements

### PR DESCRIPTION
**Pull request by Krisseck**
# [AU-819](https://helsinkisolutionoffice.atlassian.net/browse/AU-819)

## What was done

* Small improvements to robot test code for readability
* Biggest change is that now the tests create a fullpage screenshot on failure, in addition to the small, viewport-sized screenshot by default.
* Added tests for "KuVa-projekti" forms

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-0000_insert_correct_branch`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] `make test-robot`

[AU-819]: https://helsinkisolutionoffice.atlassian.net/browse/AU-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jiisuominen — CHANGES_REQUESTED** [review]
Does not pass.
[logs.zip](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/files/11621430/logs.zip)

Also still using default testing HETU & business. I'm pretty sure I've suggested many times not to use that. To take some (basically any) other hetu from those 10K testing hetus we have available.

**Comment by jiisuominen** [comment]
Actually, here's the test data. Pick one and verify testing email.

[data.zip](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/files/11621456/data.zip)

**Comment by Krisseck** [comment]
> Does not pass. [logs.zip](https://github.com/City-of-Helsinki/hel-fi-drupal-grants/files/11621430/logs.zip)
> 
> Also still using default testing HETU & business. I'm pretty sure I've suggested many times not to use that. To take some (basically any) other hetu from those 10K testing hetus we have available.

Updated the default test HETU and profile, try running the tests again.

**Review by jiisuominen — APPROVED** [review]
Ei mee vieläkään läpi. Mut pitää tarkastella noita testejä ku saatu lomakemuutokset stabiileiks

**Pull request merged**
